//
// Created by hwf on 2023/7/19.
//

#ifndef MACH_READER_TESTS_FOR_TEST_PROJECTS_HELLO_HELLO_H_
#define MACH_READER_TESTS_FOR_TEST_PROJECTS_HELLO_HELLO_H_
void hello();
#endif //MACH_READER_TESTS_FOR_TEST_PROJECTS_HELLO_HELLO_H_
